# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maciej Myśliński
email: hello@maciejmyslinski.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maciejmyslinski.com" # the base hostname & protocol for your site
twitter_username: maciejmyslinski
github_username:  maciejmyslinski
port: 3000 # change server port to 3000

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - gulpfile.js
  - bower.json
  - Gemfile
  - Gemfile.lock
  - package.json

include: ["_pages"]

gems:
  - jekyll-assets

assets:
  compress:
    css: true
  assets:
    - "*.jpg"
    - "favicon/*.*"
  sources:
    - _assets/bower
  autoprefixer:
    browsers:
      - "> 1%"
